### ISSUE TITLE
sketch-fusion-extension-plugin-webpack

### ISSUE THREAD

**Issue by tehfailsafe** [turbobabr/sketch-wanderer#1]
Interested in this, where is the source for this webpack plugin?

**Comment by turbobabr** [comment]
Hey Mike! The webpack plugin isn't available yet. I'm going to publish it on `github/npm` sooner or later. Meanwhile, if you need a ES6 and npm modules support in your plugins - check out this project:
https://github.com/mathieudutour/git-sketch-plugin

**Comment by tehfailsafe** [comment]
Ah, I hope it's soon!
The project above looks interesting, but isn't it for designers using git to visually dif? How could it be used to webpack/bundle external npm modules into a plugin?

I setup the basic webpack flow directly in the sketch.plugin dir, with this in my config:

```
output: {
        path: 'Contents/Sketch/',
        filename: 'plugin.js',
        library: "Plugin",
        libraryTarget: 'var'
    },
```


It throws lots of errors about "onRun" not exising unless I add `module.exports = (context) => ` as my plugin, but that means I can only export a single function, and any sort of "Plugin.otherMethod" can't be found from the manifest...

Any ideas until you push your plugin?
