### ISSUE TITLE
Select Up / Down identical mapping with Mission Control

### ISSUE THREAD

**Issue by PeterEmil** [turbobabr/sketch-wanderer#2]
I use Mission Control and even when Shortcuts Schema is on "control+option+arrows" I can't use "select up" and / or "select down" because of its identical mapping with Mission Control. See attached screenshot.
<img width="723" alt="screen shot 2017-03-20 at 20 56 21" src="https://cloud.githubusercontent.com/assets/2565012/24118908/bdf1f58c-0daf-11e7-9622-0a17968d4ceb.png">

BTW Super delighted I stumbled upon your plugin. Sweet.

**Comment by turbobabr** [comment]
Wow! Just checked it, indeed.. mission control grabs `shift` as well for that super useless slow-mo transition. Not sure which set of shortcuts could be used as a replacement 🤔

**Comment by PeterEmil** [comment]
Too bad we can't change shortcuts of Mission Control... or can we? Is using the shortcuts `alt + shift + up/down arrows` an idea?

**Comment by PeterEmil** [comment]
I ended up changing my shortcut mappings for Mission Control to take use of the expanded keyboard, so they are all in the range of F16 to F19. That seems to work flawless.
![screenshot 2017-03-23 13 16 40](https://cloud.githubusercontent.com/assets/2565012/24247200/07bc215c-0fcb-11e7-96bf-e84a0f80cfa6.png)
![screenshot 2017-03-23 13 16 58](https://cloud.githubusercontent.com/assets/2565012/24247201/07dc68cc-0fcb-11e7-9304-9924281e57f1.png)

**Comment by turbobabr** [comment]
Oops... sorry, missed your previous comment. `option + shift + up/down arrows` shortcuts aren't going to work since `command` or `control` keys are required to form a shortcut. `option` and `shift` keys are just modifiers used as an addition to controlling key.

Anyway, glad you found workaround! 👍
